config/routes.rb
Rails.application.routes.draw do
  resources :land_informations

  root 'main#index'

end

app/models/land_information.rb
class LandInformation < ActiveRecord::Base
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/land_informations_controller.rb
class LandInformationsController < ApplicationController
  before_action :set_land_information, only: [:show, :edit, :update, :destroy]

  # GET /land_informations
  # GET /land_informations.json
  def index
    @land_informations = LandInformation.all
  end

  # GET /land_informations/1
  # GET /land_informations/1.json
  def show
  end

  # GET /land_informations/new
  def new
    @land_information = LandInformation.new
  end

  # GET /land_informations/1/edit
  def edit
  end

  # POST /land_informations
  # POST /land_informations.json
  def create
    @land_information = LandInformation.new(land_information_params)

    respond_to do |format|
      if @land_information.save
        format.html { redirect_to @land_information, notice: 'Land information was successfully created.' }
        format.json { render :show, status: :created, location: @land_information }
      else
        format.html { render :new }
        format.json { render json: @land_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /land_informations/1
  # PATCH/PUT /land_informations/1.json
  def update
    respond_to do |format|
      if @land_information.update(land_information_params)
        format.html { redirect_to @land_information, notice: 'Land information was successfully updated.' }
        format.json { render :show, status: :ok, location: @land_information }
      else
        format.html { render :edit }
        format.json { render json: @land_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /land_informations/1
  # DELETE /land_informations/1.json
  def destroy
    @land_information.destroy
    respond_to do |format|
      format.html { redirect_to land_informations_url, notice: 'Land information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_land_information
      @land_information = LandInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def land_information_params
      params.require(:land_information).permit(:address, :latitude, :longitude, :price_per_square_meters, :product_type, :price, :area)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @land_informations = LandInformation.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/land_informations_helper.rb
module LandInformationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/land_informations/_form.html.erb
<%= form_for(@land_information) do |f| %>
  <% if @land_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@land_information.errors.count, "error") %> prohibited this land_information from being saved:</h2>

      <ul>
      <% @land_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :price_per_square_meters %><br>
    <%= f.number_field :price_per_square_meters %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/land_informations/edit.html.erb
<h1>Editing land_information</h1>

<%= render 'form' %>

<%= link_to 'Show', @land_information %> |
<%= link_to 'Back', land_informations_path %>

app/views/land_informations/index.html.erb
<h1>Listing land_informations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Price per square meters</th>
      <th>Product type</th>
      <th>Price</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @land_informations.each do |land_information| %>
      <tr>
        <td><%= land_information.address %></td>
        <td><%= land_information.latitude %></td>
        <td><%= land_information.longitude %></td>
        <td><%= land_information.price_per_square_meters %></td>
        <td><%= land_information.product_type %></td>
        <td><%= land_information.price %></td>
        <td><%= land_information.area %></td>
        <td><%= link_to 'Show', land_information %></td>
        <td><%= link_to 'Edit', edit_land_information_path(land_information) %></td>
        <td><%= link_to 'Destroy', land_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Land information', new_land_information_path %>

app/views/land_informations/new.html.erb
<h1>New land_information</h1>

<%= render 'form' %>

<%= link_to 'Back', land_informations_path %>

app/views/land_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @land_information.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @land_information.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @land_information.longitude %>
</p>

<p>
  <strong>Price per square meters:</strong>
  <%= @land_information.price_per_square_meters %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @land_information.product_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @land_information.price %>
</p>

<p>
  <strong>Area:</strong>
  <%= @land_information.area %>
</p>

<%= link_to 'Edit', edit_land_information_path(@land_information) %> |
<%= link_to 'Back', land_informations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandInfo</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src='//maps.googleapis.com/maps/api/js?sensor=false'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div ng-app="landInfoApp">
  <div ng-controller="landInfoCtrl">
    <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable='true'>
      <ui-gmap-marker idkey="$index"
        coords="{latitude: land_info.latitude, longitude: land_info.longitude}"
        icon="'http://chart.apis.google.com/chart?chst=d_map_spin&chld=1|0|FF0000|12|_|' + get_price(land_info) + '萬'"
        ng-repeat="land_info in land_informations"
        click="openWindow(land_info)">
      </ui-gmap-marker>
    </ui-gmap-google-map>
  </div>
</div>

<script>
  var landInfoApp = angular.module('landInfoApp', ['uiGmapgoogle-maps', 'ui.bootstrap']);
  landInfoApp.controller('landInfoCtrl', function($scope, $modal, $http) {
    $scope.map = {
        center: {
            latitude: '25.0392179',
            longitude: '121.5398562'
        },
        zoom: 15
    };

    $scope.openWindow = function(land_info){
      var modalInstance = $modal.open({
        templateUrl: 'landInfoModalContent.html',
        controller: ModalInstanceCtrl,
        size: 'm',
        resolve: {
          land_info: function () {
            return land_info;
          }
        }
      });
    };

    $scope.get_price = function(land_info) {
      return Math.ceil((land_info.price_per_square_meters / 1000) * (121 / 400));
    };

    $scope.land_informations = <%= LandInformation.all.to_json.html_safe %>;
  });

  var ModalInstanceCtrl = function ($scope, $modalInstance, land_info) {
    $scope.land_info = land_info;

    $scope.ok = function() {
      $modalInstance.dismiss('cancel');
    };
  };
</script>

<style>
.angular-google-map-container { height: 800px; }

.marker-labels {
  padding: 2px 0;
  width: 150px;
  text-align: center;

  background-color: white;
  color: red;
  border: black 1px solid;
}
</style>